title: Apollo
email: martin@moonwalkingbits.com
description: >-
    The Apollo project is an effort to bring stability to Node.js projects at scale.
baseurl: ""
url: "http://apollo.moonwalkingbits.com"
github_username:  moonwalkingbits
